/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";
// import Profile from "../component/Profile";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*Render the profile Component here */}
      {/* <Profile /> */}

      {/*Make a <div> for profile Section */}
      <div className="flex flex-col text-center items-start sm:text-left sm:items-center sm:flex-row sm:p-4">

        {/*Create a Div for NOTIFICATION ICON, put image inside that */}
        <div className="relative">
          <div className="sm:absolute bg-orange-400 h-10 w-10 rounded-full animate-pulse "/>
        <img
          className="cursor-pointer m-1  h-48 w-48 sm:ring-4 ring-red-400 sm:h-56 sm:w-56 sm:rounded-full sm:ml-2 "
          src="https://0.academia-photos.com/129166164/35825769/35696192/s200_vinay.choudhary.jpg"
          alt="profile picture"
        />
        </div>
        <div className="m-2 text-left sm:ml-4">
          <h1 className="text-xl sm:text-2xl">Vinay Choudhary</h1>
          <h2 className="text-xl sm:text-xl">Software Engineer</h2>
        </div>
      </div>

      {/*Create two buttons */}
      <div className="flex gap-3 items-center ml-2 sm:ml-10">
        <button className="h-12 w-24 sm:h-12 sm:w-28 rounded-2xl shadow-lg ring-2 ring-green-300 hover:ring-green-800 focus:outline-none">
          Create a Todo
        </button>
        <button className="h-6 w-16 sm:h-7 sm:w-16 rounded-2xl shadow-lg ring-2 ring-red-300 hover:ring-red-800 focus:outline-none">
          Delete
        </button>
      </div>
    </div>
  );
}
